spring:
  profiles:
    active: local
    include: 'security, db, management'
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: false
    add-properties: false
  jmx:
    enabled: false
  main:
    banner-mode: off
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration, org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
  session:
    store-type: mongodb

server:
  port: 8080
  error:
    whitelabel:
      enabled: false

logging:
  level:
    org.springframework: INFO
    org.springframework.web: DEBUG
    com.underbell: DEBUG

# dev env
---
spring:
  profiles: dev
  devtools:
    restart:
      enabled: false

server:
  http2:
    enabled: true
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 1024
  forward-headers-strategy: native

# prod env
---
spring:
  profiles: prod
  devtools:
    restart:
      enabled: false

server:
  http2:
    enabled: true
  error:
    include-stacktrace: never
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 1024
  forward-headers-strategy: native