spring:
  jpa:
    open-in-view: false
  data:
    mongodb:
      auto-index-creation: false

# local env
---
spring:
  profiles: local
  data:
    mongodb:
      url: mongodb://admin:password@localhost:27017/test
      database: test

# dev env
---
spring:
  profiles: dev
  data:
    mongodb:
      url: mongodb://admin:password@localhost:27017/test
      database: test

# prod env
---
spring:
  profiles: prod
  data:
    mongodb:
      url: mongodb://admin:password@localhost:27017/test
      database: test