version: "3"
services:
  mongodb:
    restart: always
    image: mongo:4.2
    container_name: mongo-db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=test
    ports:
      - '27017:27017'
    volumes:
      - ./volumes/mongo:/data/db
      - ./mongoinit/:/docker-entrypoint-initdb.d